language: node_js
node_js:
- 10
after_success: npm run coverage && npm run build
deploy:
  provider: npm
  on:
    tags: true
  skip_cleanup: true
  email: michal@perlakowski.pl
  api_key:
    - secure: y7zk3QxxVPepMJhTcUD2PtNB4QFdP0WBWykI0MxTSbhixITHjIq0bANEhN9NnMOB4o8+aLvZ7v6VB2+lubE144pqgECvXbXFQXit7dQkcv/JTGoVPUpMIqzKZ4sOIzQHlE9V82dQUEhEHQyaLOxR2ijj39xrGLhA5t8D+25mlv+rSRaoDhTMGFz9MvGPNyHmTbgskAHRyOwV4e9gH7UyKscMc30Be64UEbD14F+XOdHInZX6TidBKIJIiBKDSp9VYlRogUGMM7bFgdjoZ2/y84Is8U7tCiB4WzXgVV5B8o/lEYwcYlQ73FOg238YGW0yK+rTOLKJLNLcG4U6l2sKVBqFC2N7EwAO2EHwSDoj5kJ42u5Eam2ddagoJUqM5sL/0222y9h6vyOe5jS0Fa+SGotj7Ypm2KU0F/2/tqUHoX58T0d5/pivcRK7i7s5lQUkxhrqvnV8WmFyoAsxBnAOPRJWCv/Rxq6r3qrB7PLbUCzRpTDNKV4j5srbOluOlrjby3Y99VAHojRzcxLVaLQhLlhb+2V8KL1/SGZTiHWvF8BbjtqxsefEvbhyvEZRC5g43hf6iYerK/bWN5ap+Yd8g0HjO48syN471utoCINNSmjLKUV9KYWW7Ozs+blDGJT4KAgiQtSdkkxLny7OurhWF+ex0jRseDDH9/veGg1sCow=
