language: node_js
node_js:
- 10
after_success: npm run coverage && npm run build
deploy:
  provider: npm
  on:
    tags: true
  skip_cleanup: true
  email: michal@perlakowski.pl
  api_key:
    secure: Q2sLOL3yUWT8IRJAspegV+W/TU4Kh7/L3S1UC4mbdfgtuxysD/nxz9Oo5c5UzZljVVRmAB2zDtOn/crEwDI2QVFvG4JXEYH+M5U38h7c+JSt5CjzzZ84aN4POBmJW2/MUb7prOIxLXFC/7psi9JQnQsE9hXWLIN5Gcy6d+jXqyqDHCTp9Tbvkz2JDYhCsy/lWVVt5Gc/+C8v0/nUF8FkCl6C3ttFLfErq/dMhnaIW7AE60V5CYB4xG2dz8hR8l5yWADn8UAN/hWvwVANMWpeaf51R8hjtgL4xE9nhmMHaP/3D90KtKrZ/+WP/IH6xJLqxP457IVzzlXR6BDfAcFUIwRlxzvYHVqwOS07y9mig6OjFxi004+kO/f9N5SENZetYv8kVwc8gpWerzmKdx+cWyzAtpPm+9RhiLdvp0HmR+Ttx+qR1lo1vIlz8cJfzR+1bxzejORvwsisaQML61RT9FVVB8E6QQjKHUiZBEmv5GdGYqbEnh+SYnYZJ0i/qOx4JlcBXbNI8gCcbwP3Yuf1i+k8VxdCPgopyOb3Y4bZK70vnUkTHCpDa6vxOqhMQ02RiiSk0E+w+OXytO4ctmSUiHsyFgsDzw92D/ucB68a7WYG8uuQIBID0IrKX2j3DkJ3g3icJgS40y9q+mNhbCtnO0eHk+bzFhVkM7mVcsq0o8g=
